### ISSUE TITLE
CSS Selectors and declarations written on separate lines

### ISSUE THREAD

**Issue by zannain** [weedfield/prj-rev-bwfs-dasmoto#3]
I recommend checking out the [CSS style guide](https://google.github.io/styleguide/htmlcssguide.html) to pick up best practices when writing CSS. Selectors and declarations should go on separate lines.

```css
h1, header, .price, h3{font-family:Helvetica;
                       font-weight: bold;}
```

```css
h1, 
header, 
.price, 
h3 {
    font-family:Helvetica;
    font-weight: bold;
}
```
